### ISSUE TITLE
UI Scale will cause Slot Machine's buttons to be misaligned

### ISSUE THREAD

**Issue by Linnnnnna** [GabeHasWon/SpiritMod#1]
![SEIMHH(5$OVN0IY27BQV_OX](https://github.com/GabeHasWon/SpiritMod/assets/63439268/34aed608-2cac-4353-be5b-8967388dfcdb)
![TVPFR@$O4ZSKDZ30XCL4PSU](https://github.com/GabeHasWon/SpiritMod/assets/63439268/9bf88503-73e1-4087-a195-edce6fc9b0e4)
---
![1CN%V2HD4)H1P2RQKBO{V4L](https://github.com/GabeHasWon/SpiritMod/assets/63439268/aec4ad2e-b361-4fab-bd16-a551541c7ea3)
![HN7EFT(Z(56PI@ K7@0VD9T](https://github.com/GabeHasWon/SpiritMod/assets/63439268/469f0987-3ab8-4e57-88b2-b77a1e6dfe1a)
@GabeHasWon

**Comment by GabeHasWon** [comment]
Fixed in next hotfix! That should finally be the end of me chasing issues with this UI lol. Thanks!
