### ISSUE TITLE
Atlas Moving Above the Map when One Player Dies

### ISSUE THREAD

**Issue by silvernull** [GabeHasWon/SpiritMod#31]
#### Mod Version
v1.5.0.14
#### Terraria and tMod Version
v1.4.4.9 and v2024.2.3.0
#### Terraria and tMod Version
1.4.4.9
### Steps to Recreate
1. Open a World
2. Summon Atlas on the Surface
3. Let one player in Atlas' Aggro radius die
4. Atlas Rapidly moves above the Map
#### Further Details
Not sure if Multiplayer, 
Multiple Players, 
or being in Aggro Radius are required, does not seem to be the case.

Behavior might be dependent on the Depth/Height of Atlas or the Players at time of Player Death (seems to be the case).

#### Other Enabled Mods
Better Zoom
Shift-Click Crafting
Tome of Research Sharing
Realistic Sky
Concise Mods List
Smarter Cursor
Particle Library
Heart Crystal & Life Fruit Glow
High FPS Support
Recipe Browser
Echo Dye
Fancy Lighting
Instant Platform Fallthrough
DragonVault
imkSushi's Mod
ArmamentDisplay
ShorterRespawnTime
Max Luck
Auto Trash

**Comment by GabeHasWon** [comment]
Fixed incidentally in a prior hotfix.
