### ISSUE TITLE
Ethereal Ember Sprite is Darker than Intended

### ISSUE THREAD

**Issue by silvernull** [GabeHasWon/SpiritMod#33]
#### Mod Version
v1.5.0.14
#### Terraria and tMod Version
v1.4.4.9 and v2024.2.3.0
### Steps to Recreate
1. Open a World
2. Acquire an Ethereal Ember
3. Sprite is Darker than Original in all Instances
#### Further Details
Side by Side, 
Original on Left, 
Maximum Ingame Brightness on Right

![image](https://github.com/GabeHasWon/SpiritMod/assets/80038133/f066b0ce-bbaf-4bf6-9eae-c13ddec9e4dc)

#### Other Enabled Mods
Better Zoom
Shift-Click Crafting
Tome of Research Sharing
Realistic Sky
Concise Mods List
Smarter Cursor
Particle Library
Heart Crystal & Life Fruit Glow
High FPS Support
Recipe Browser
Echo Dye
Fancy Lighting
Instant Platform Fallthrough
DragonVault
imkSushi's Mod
ArmamentDisplay
ShorterRespawnTime
Max Luck
Auto Trash

**Comment by GabeHasWon** [comment]
This seems to be intentional for some reason, the color of the item is set to rgb 180, 180, 180. I just made it 255, 255, 255 because why is it slightly darker?
