### ISSUE TITLE
Kelp Generating 

### ISSUE THREAD

**Issue by silvernull** [GabeHasWon/SpiritMod#38]
#### Mod Version
v1.5.0.14
#### Terraria and tMod Version
v1.4.4.9 and v2024.2.3.0
### Steps to Recreate
Unknown
#### Further Details
Kelp breaks Platforms and can Generate Through Blocks.
Also sometimes? seems to Generate on Slopes and Break Instantly.
![image](https://github.com/GabeHasWon/SpiritMod/assets/80038133/d9382ecf-a36c-4990-8421-f99b872c716d)
#### Other Enabled Mods
Better Zoom
Shift-Click Crafting
Tome of Research Sharing
Realistic Sky
Concise Mods List
Smarter Cursor
Particle Library
Heart Crystal & Life Fruit Glow
High FPS Support
Recipe Browser
Echo Dye
Fancy Lighting
Instant Platform Fallthrough
DragonVault
imkSushi's Mod
ArmamentDisplay
ShorterRespawnTime
Max Luck
Auto Trash

**Comment by GabeHasWon** [comment]
Half of this was fixed a long time ago. Also fixed it generating on slopes then dying!
