### ISSUE TITLE
Tombstones can drop on Naturalist's Workshop

### ISSUE THREAD

**Issue by silvernull** [GabeHasWon/SpiritMod#43]
#### Mod Version
v1.5.0.14
#### Terraria and tMod Version
v1.4.4.9 and v2024.2.3.0
### Steps to Recreate
1. Open a World
2. Die so that a Tombstone drops on a Naturalist's Workshop
#### Further Details
Works in Single and Multiplayer.
![image](https://github.com/GabeHasWon/SpiritMod/assets/80038133/0974f83b-3eb2-43b6-8bee-7fc62cf48813) ![image](https://github.com/GabeHasWon/SpiritMod/assets/80038133/99eaebd7-a445-4557-9baa-23a648e82768)
#### Other Enabled Mods
Better Zoom
Shift-Click Crafting
Tome of Research Sharing
Realistic Sky
Concise Mods List
Smarter Cursor
Particle Library
Heart Crystal & Life Fruit Glow
High FPS Support
Recipe Browser
Echo Dye
Fancy Lighting
Instant Platform Fallthrough
DragonVault
imkSushi's Mod
ArmamentDisplay
ShorterRespawnTime
Max Luck
Auto Trash

**Comment by GabeHasWon** [comment]
Fixed. Turns out it also required an anchor of 2 tiles despite being 3 tiles wide. Thanks!
